name: Trigger auto deployment for ca-ozoblockly-editor

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-ozoblockly-editor-AutoDeployTrigger-ee5ca3f3-e8f5-4310-8020-4f28d8268057.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAOZOBLOCKLYEDITOR_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.CAOZOBLOCKLYEDITOR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAOZOBLOCKLYEDITOR_REGISTRY_PASSWORD }}
          containerAppName: ca-ozoblockly-editor
          resourceGroup: rg-ozoblockly-editor
          imageToBuild: ghcr.io/johannesegger/ozoblockly-translations:${{ github.sha }}
          

     

