name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_BASE_NAME: ozoblockly-translations
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Create Docker image
      run: dotnet publish --verbosity normal --os linux --arch x64 -p:PublishProfile=DefaultContainer -p:ContainerImageName=$DOCKER_IMAGE_BASE_NAME -p:ContainerImageTags=latest
    - name: Push Docker image
      env:
        DOCKER_IMAGE_FULL_NAME: ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.DOCKER_IMAGE_BASE_NAME }}
      run: |
        docker image tag $DOCKER_IMAGE_BASE_NAME $DOCKER_IMAGE_FULL_NAME:$GITHUB_REF_NAME
        docker image tag $DOCKER_IMAGE_BASE_NAME $DOCKER_IMAGE_FULL_NAME:latest
        docker push --all-tags $DOCKER_IMAGE_FULL_NAME
