name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_BASE_NAME: ozoblockly-translations
      DOCKER_IMAGE_FULL_NAME: ghcr.io/${{ github.REPOSITORY }}
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Create Docker image
      run: dotnet publish --verbosity normal --os linux --arch x64 -p:PublishProfile=DefaultContainer -p:ContainerImageName=$DOCKER_IMAGE_BASE_NAME -p:ContainerImageTags=latest
    - name: Login to GitHub Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: $GITHUB_REPOSITORY_OWNER
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image
      run: |
        docker image tag $DOCKER_IMAGE_BASE_NAME $DOCKER_IMAGE_FULL_NAME:$GITHUB_REF_NAME
        docker image tag $DOCKER_IMAGE_BASE_NAME $DOCKER_IMAGE_FULL_NAME:latest
        docker push --all-tags $DOCKER_IMAGE_FULL_NAME
    - name: Update Azure Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
        imageToDeploy: $DOCKER_IMAGE_FULL_NAME
        resourceGroup: rg-ozoblockly-editor
        containerAppEnvironment: cae-ozoblockly-editor
        containerAppName: ca-ozoblockly-editor

